mongoDB:
  dbname: fitbit
  host: localhost
  port: 27017

accesstoken:
  clientid: 227MLG
  grantType: authorization_code
  redirectUri: http://localhost:8080
  headerAuth: Basic MjI3TUxHOjlkNTUwNjIxYzBlZTQ0ODkzNGM4MDQxYzQ1NjA3MTcx
  headerAccept: application/json
  authCodeUri: https://www.fitbit.com/oauth2/authorize?redirect_uri=http://localhost:8080&response_type=code&client_id=227MLG&scope=activity%20nutrition%20heartrate%20profile%20settings%20sleep%20social%20weight&expires_in=2592000&prompt=login

mailInfo:
  username: nickma72@gmail.com
  password: mastronikos
  fileName: heartRatePeaks.txt
  sendTo: n.mastrogiannopoulos@logicea.com
  sendFrom: nickma72@gmail.com