# mongo database required credentials
mongoDB:
  dbname: fitbit
  host: localhost
  port: 27017

# access token credentials and authorization code uri
accesstoken:
  grantType: authorization_code
  redirectUri: http://localhost:8080
  headerAccept: application/json
  authCodeUri1: https://www.fitbit.com/oauth2/authorize?redirect_uri=http://localhost:8080&response_type=code&
  authCodeUri2: scope=activity%20nutrition%20heartrate%20profile%20settings%20sleep%20social%20weight&expires_in=3600&prompt=login

# refresh token credentials
refreshtoken:
  grantType: refresh_token
  headerAccept: application/json

# e-mail credentials 
mailInfo:
  username: nickma72@gmail.com
  password: mastronikos
  fileName: heartRatePeaks.txt
  sendFrom: nickma72@gmail.com